### ISSUE TITLE
Check if input is valid

### ISSUE THREAD

**Issue by endrinar** [GCMLab/GCMLab-FEM#30]
Write a script to check config files for correctness. This is partly done in setDefaults.m now, but can be enhanced.
i.e. check whether material properties are within a valid range, check whether other inputs are of correct data type and size, etc.

**Comment by b3gee** [comment]
I have opened up a branch entitled **sanitize-input** to start addressing this issue

- I have added error messages to _getK_ and _getD_ to catch negative Jacobians and incorrect **D** specifications
- I have added a separate function to check for valid inputs. So far it check for
       - Non-negative ranges of E, nu, t
       - Prescribed nodes or DoFs which are either negative or greater than the total number of nodes.

To add: correct data dimension type and size

What other conditions should we check for?
