### ISSUE TITLE
"Directory for VTK Files" in RunSim

### ISSUE THREAD

**Issue by LiLi-Geo** [GCMLab/GCMLab-FEM#43]
I was wondering if we modified the "Directory for VTK Files" to the code below, so it can cover the major platforms.  

if ismac
    % Code to run on Mac platform
    VTKFolder = '..../Matlab Results/';
elseif isunix
    % Code to run on Linux platform
    VTKFolder = '..../Matlab Results/';
elseif ispc
    % Code to run on Windows platform
    VTKFolder ='..../Matlab Results/';
end

**Comment by endrinar** [comment]
The main difference is in the forward-slash or back-slash. Do you know which way the mac file paths are defined?

**Comment by LiLi-Geo** [comment]
> The main difference is in the forward-slash or back-slash. Do you know which way the mac file paths are defined?

I tried forward-slash or back-slash in windows, they are both working, but don't know if it is the same on mac...

**Comment by endrinar** [comment]
Hmmm.. if it works either way, then maybe we can just omit the if-statement and each user can specify their own paths?

**Comment by LiLi-Geo** [comment]
> Hmmm.. if it works either way, then maybe we can just omit the if-statement and each user can specify their own paths?

That is a good idea. :)
